name: Run test suites

on:
  push:
    branches:
      - main

jobs:
  generate-test-run-id:
    name: Generate Test Run ID
    runs-on: ubuntu-latest
    steps:
      - id: uuid
        run: |
          echo "ubuntu-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
          echo "macos-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
          echo "windows-latest-id=$(npx uuid)" >> "$GITHUB_OUTPUT"
    outputs:
      ubuntu-latest-testRunId: ${{ steps.uuid.outputs.ubuntu-latest-id }}
      macos-latest-testRunId: ${{ steps.uuid.outputs.macos-latest-id }}
      windows-latest-testRunId: ${{ steps.uuid.outputs.windows-latest-id }}
  e2etest:
    name: End-to-end tests (${{ matrix.shard }})
    runs-on: ubuntu-latest
    needs: [generate-test-run-id]
    strategy:
      # GH cancels other matrixed jobs by default if one fails. We want all E2E jobs to complete.
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 20
    steps:
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: console.log("ENV =", process.env.RECORD_REPLAY_METADATA_TEST_RUN_ID)
        env:
          RECORD_REPLAY_METADATA_TEST_RUN_ID: ${{ needs.generate-test-run-id.outputs[matrix.platform + "testRunId"] }}
  